image: node:lts

cache:
  paths:
    - node_modules/

before_script:
  - mkdir -p ~/.ssh
  - 'which rsync || ( apt update -y -qq && apt install rsync -y -qq )'
  - eval $(ssh-agent -s)
  - echo "$SQRD_DEVOPS_KEY" | tr -d '\r' | ssh-add -

pages:
  script:
    - yarn install
    - yarn build
    - rsync -e "ssh -o StrictHostKeyChecking=no" -arP --delete public/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DESTINATION"
  only:
    - master
  tags:
    - docker-executor
    - linux
