image: node:lts

cache:
  paths:
    - node_modules/

before_script:
  - mkdir -p ~/.ssh
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SQRD_DEVOPS_KEY" | tr -d '\r' | ssh-add -

pages:
  script:
    - yarn install
    - yarn build
    - scp -o StrictHostKeyChecking=no -r public/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DESTINATION"
  only:
    - master
  tags:
    - docker-executor
    - linux
